---
- name: Converge
  hosts: all
  roles:
    - role: genlab.wg_spoke
      iface_name: adm
      spoke_ipv4_vpn: "10.0.0.1"
      subnet: "10.0.0.0"
      netmask: "24"
      spoke_pkey: eGqGx4A5ufFKatLflPFKNuzFgGuospIe08iPbTlEhm0=
      hub_pubkey: EvcoZ21/p0AHz5y95jwjVIR9puljc2kXqh/f3U1A4nk=
      hub_ipv4_wan: "1.2.3.4"
      hub_ipv4_vpn: "10.0.0.254"
      hub_port: "51820"
      hide_secrets: false
